export const canineBreeds: string[] = [
  "Labrador Retriever",
  "Golden Retriever",
  "Pastor Alemán",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Poodle (Caniche)",
  "Beagle",
  "Rottweiler",
  "Yorkshire Terrier",
  "Boxer",
  "Dachshund (Salchicha)",
  "Schnauzer Miniatura",
  "Schnauzer Estándar",
  "Shih Tzu",
  "Chihuahua",
  "Pomerania",
  "Doberman",
  "Gran Danés",
  "Husky Siberiano",
  "Border Collie",
  "Cocker Spaniel",
  "Basset Hound",
  "Pug",
  "Maltés",
  "Bichón Frisé",
  "Boston Terrier",
  "Akita",
  "Pastor Belga Malinois",
  "San Bernardo",
  "Dálmata",
  "Weimaraner",
  "Whippet",
  "Galgo",
  "Setter Irlandés",
  "Pointer",
  "Braco Alemán",
  "Cane Corso",
  "Mastín Napolitano",
  "Bull Terrier",
  "Staffordshire Terrier",
  "American Pit Bull Terrier",
  "Jack Russell Terrier",
  "West Highland White Terrier",
  "Cairn Terrier",
  "Fox Terrier",
  "Papillón",
  "Shar Pei",
  "Chow Chow",
  "Samoyedo",
  "Alaskan Malamute",
  "Collie",
  "Old English Sheepdog",
  "Corgi Galés",
  "Basenji",
  "Rhodesian Ridgeback",
  "Vizsla",
  "Terranova",
  "Lhasa Apso",
  "Perro Sin Pelo del Perú",
  "Xoloitzcuintle",
  "Criollo / Mestizo",
];

export const felineBreeds: string[] = [
  "Criollo / Mestizo",
  "Persa",
  "Siamés",
  "Maine Coon",
  "Angora Turco",
  "British Shorthair",
  "Bengalí",
  "Ragdoll",
  "Sphynx",
  "Abisinio",
  "Birmano",
  "Exótico de Pelo Corto",
  "Devon Rex",
  "Cornish Rex",
  "Scottish Fold",
  "Himalayo",
  "Azul Ruso",
  "Bombay",
  "Burmés",
  "Manx",
  "Oriental",
  "Somalí",
  "Ragamuffin",
  "American Shorthair",
  "Nebelung",
  "Munchkin",
];

export const vaccines = [
  {
    name: "Séxtuple canina",
    species: "CANINO" as const,
    description:
      "Moquillo, hepatitis, parvovirus, parainfluenza, adenovirus y leptospirosis.",
    boosterIntervalDays: 365,
    initialSeriesDays: [0, 21, 42],
  },
  {
    name: "Rabia",
    species: "CANINO" as const,
    description: "Vacuna antirrábica canina.",
    boosterIntervalDays: 365,
    initialSeriesDays: [0],
  },
  {
    name: "Tos de las perreras",
    species: "CANINO" as const,
    description: "Bordetella bronchiseptica / parainfluenza.",
    boosterIntervalDays: 365,
    initialSeriesDays: [0],
  },
  {
    name: "Triple felina",
    species: "FELINO" as const,
    description: "Panleucopenia, rinotraqueítis y calicivirus felino.",
    boosterIntervalDays: 365,
    initialSeriesDays: [0, 21, 42],
  },
  {
    name: "Leucemia felina",
    species: "FELINO" as const,
    description: "Virus de la leucemia felina (FeLV).",
    boosterIntervalDays: 365,
    initialSeriesDays: [0, 21],
  },
  {
    name: "Rabia",
    species: "FELINO" as const,
    description: "Vacuna antirrábica felina.",
    boosterIntervalDays: 365,
    initialSeriesDays: [0],
  },
];
